name: uni_plus
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Supabase and State Management
  supabase_flutter: ^2.5.0
  flutter_riverpod: ^2.5.1
  
  # Storage and Localization
  flutter_secure_storage: ^9.0.0
  intl: ^0.20.2

  # Restored Dependencies
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0
  excel: ^4.0.0
  path_provider: ^2.1.2
  open_file: ^3.5.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  image_path: "assets/icons/uniplus_icon1.png"

flutter:
  generate: false
  uses-material-design: true
  assets:
    - assets/icons/uniplus_icon1.png
    - assets/icons/uniplus_icon1.png
